### ISSUE TITLE
NO SMITE BUTTON REEE

### ISSUE THREAD

**Issue by SplergeBucket** [HippieStationArchive/HippieStation13-2#101]
WE SHOULD HAVE A SMITE BUTTON
I RIGHT CLICK A CUNT
I HAVE THE OPTION TO SMITE
IT HAD ALL THE DAMAGES
AND A GIB OPTION
ADD IT BACK

**Comment by SplergeBucket** [comment]
THE MOST IMPORTANT THING ABOUT IT WAS THE LIGHTNING STRIKE EFFECT ON PEOPLE OK

**Comment by KittyKathy** [comment]
All caps RAGE...I think this is might be the most effective way to get coders to get stuff done.

**Comment by tortellinitony** [comment]
There is one on prayers now, I think it's accessible some other way but not sure. Also, you can gib and deal damage in the VV menu, so..
