### ISSUE TITLE
Setting your chameleon thermals to "glasses" makes them invisible.

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStationArchive/HippieStation13-2#113]
They end up with no sprite but can be seen via right click and taken off via strip ui or just clicking the eyewear slot.

**Comment by j-mie** [comment]
Came across this yesterday - thought it was intended 😂

**Comment by JohnGinnane** [comment]
This is because "glasses" seem to be broken too

**Comment by JohnGinnane** [comment]
Looks like upstream issue, /tg/'s fancy chameleon is including the base "glasses" which have no icon_state
