### ISSUE TITLE
Mech Race Issues

### ISSUE THREAD

**Issue by JohnMcLaime** [HippieStationArchive/HippieStation13-2#118]
They can bleed,
Arent syringe proof,
Require a lot of fuel to heal with welder and much much more time that it would take healing with brutepacks on the go,
Same with coils but they can hold more units than stock welders.
Healing chems dont work on them.
They need oxygen.
Only good stuff they get in return and according to tg wiki is robo limbs.
Can be stunned and harmed with emp(?)

Healing should be made instant if you decided to make brute/burn packs/patches take no time to apply on yourself.

**Comment by yobob591** [comment]
yeah they should at least be able to not bleed, maybe not need air but still need pressure suits/temp shit

**Comment by tortellinitony** [comment]
The parent android race has NOBREATH,RESISTHOT,RESISTCOLD,RESISTPRESSURE,NOFIRE,NOBLOOD,VIRUSIMMUNE,PIERCEIMMUNE,NOHUNGER,EASYLIMBATTACHMENT flags.

Pick and choose which ones you want, this needs head input though.

**Comment by JohnMcLaime** [comment]
Making welder and coil heals instant or buffed should be good, they take too many actions to heal, since each heals for a bit, compared to brute/burn packs which heal for 50 (?) hp instantly now. So if you decided to make healing for packs on yourself instant then make it so for welders and coils.

**Comment by yobob591** [comment]
I say we leave the wait time but make it so they have no hunger cant bleed and we are 👌

**Comment by yobob591** [comment]
personally I love the idea of different races being like different "classes" with buffs and debuffs and humans being the jack of all trades (besides cats of course). It gives people a reason to play races besides "specal snowflak"

**Comment by gumner** [comment]
you see,/VG/ made IPC'S so that they couldnt bleed or get oxyloss or even need food,but,shocks were lethal for them,indeed,i saw an IPC get one shot by a revenant using shock lights on paradise some time ago

**Comment by yobob591** [comment]
i like that idea, also i think our mech race is already weak to EMPs but id have to test that

**Comment by tortellinitony** [comment]
These should be fixed!
