### ISSUE TITLE
Some of the loading windows ain't work

### ISSUE THREAD

**Issue by Angelx113** [HippieStationArchive/HippieStation13-2#126]
![asteroid array eight](https://cloud.githubusercontent.com/assets/15094529/22818587/103da254-ef7f-11e6-8ac5-b611246c2b0f.jpg)

![procreatory object alpha](https://cloud.githubusercontent.com/assets/15094529/22818689/882a2c24-ef7f-11e6-9e2d-68e34587d923.jpg)

![procreatory object alph2a](https://cloud.githubusercontent.com/assets/15094529/22818690/890cc174-ef7f-11e6-9f41-e364cfefd3a9.jpg)

I have and issue since rebase with some of the ingame windows not loading.
FExample: Wires, the tiny craft menu in the bottom of the screen. 
It's just not loading, the loading text sits there forever.
It might be the same shit causing my lobby screen go mad.
Might be just because im using windows xp? dunno, please help.

**Comment by JohnGinnane** [comment]
Try updating Internet explorer (even if you don't use it)

**Comment by Angelx113** [comment]
I don't think i can update it, the new versions will not run on xp. Tryed EE 7,9 and some upgrade pack for EE8 which can't upgrade the version of EE i have now(probably older than me, im 29 thou)

**Comment by JohnGinnane** [comment]
Does this happen on /tg/ server or just ours?

**Comment by ghost** [comment]
stop using XP
update to latest BYOND 511

**Comment by Angelx113** [comment]
On /tg/ same problem.

**Comment by JohnGinnane** [comment]
Any chance of getting a newer OS?

**Comment by Angelx113** [comment]
lol, nope

**Comment by JohnGinnane** [comment]
Okay then I'm not too sure what we can do, since we just rebased to their code :(

**Comment by JohnGinnane** [comment]
@Angelx113 try update to internet explorer 8

**Comment by JohnGinnane** [comment]
Might have to look at some kind of compatibility mode for tgui as I believe that might be the cause (talking to guys in /tg/ IRC)

**Comment by cacogen** [comment]
You can update to Windows 10 without having to pay for it. Mine's never getting activated.

If you type Game Preferences you can also change the tgui style there, that might help

**Comment by tortellinitony** [comment]
Turn off frills in settings, update byond, internet explorer. If that doesn't work, get a modern computer.
