### ISSUE TITLE
Redunant confession booth in chapel blocks door.

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStationArchive/HippieStation13-2#129]
Why is there one confession booth at area 1 that blocks the door and does not have a counterpart booth for the chaplain to sit in when we have a full one at position 2?

![jesusducks](https://cloud.githubusercontent.com/assets/22083966/22832996/1f92bca2-efa8-11e6-876f-07b96d268e48.PNG)

**Comment by PopNotes** [comment]
I never fucking understood this, what an awful design.
+1 FICKS IT
+1 UNFUCK
+1 JEEESUS

**Comment by Pyko1** [comment]
oh looks like part of the old chapel still remained.

**Comment by Spacedong** [comment]
ficks it

**Comment by Pyko1** [comment]
should be fixed
