### ISSUE TITLE
Farting always uses the same message + duplicates the name

### ISSUE THREAD

**Issue by j-mie** [HippieStationArchive/HippieStation13-2#16]
https://share.jamiehankins.co.uk/ShareX/2017/02/2017-02-05_18-14-22.png

@tortellinitony

**Comment by tortellinitony** [comment]
ok I will fix this in the scream pr

**Comment by tortellinitony** [comment]
fixed close this

**Comment by JohnGinnane** [comment]
Fixed in https://github.com/HippieStation/HippieStation13-rebase/pull/23

@tortellinitony if you add "Fixes #issuenumber" when the PR is merged it automatically closes the issue
