### ISSUE TITLE
Hydroponics - Biogenerator no mutagen and grinder does not grind plants down anymore.

### ISSUE THREAD

**Issue by Takato26** [HippieStationArchive/HippieStation13-2#162]
Yea see title. The biogenerator has no mutagen option and the grinder does not grind plants anymore.

**Comment by KittyKathy** [comment]
Grinder thing is broken yeah going to look into that when I have time but first, I think I can add mutagen back into the biogenerator seeing as botanist just steal a chem dispenser now that the can be moved.
Also do you think it would be a good idea to add some starting mutagen to the vending machine in botany? I mean mutagen is necessary to do botany good and fast in the short rounds that are hippie so adding like 6 bottles of 50 unit mutagen to the vending machine so each botanist can get 100 units would not be a bad idea right?
There are at max 3 botanist in a round normally I think so each should get like 2 50unit bottles and they can already get unlimited mutagen by stealing a chem dispenser just need tools and to break into chemistry or ghetto chem which is annoying for people like the chemist or assistants that use those machines. Giving them some starting mutagen and a option to get more from the biogenerator should stop most of them from stealing the chem dispenser as they will not need to do that.

**Comment by Takato26** [comment]
That would be a amazing quality of life improvement for hydroponics in regards to the mutagen idea you proposed. energy regenerates slowly in the Chem dispensers and when you go through 90 unit batches to try to get certain mutations it its possible to burn through that energy. Thanks for working on this though.
