### ISSUE TITLE
staff can leave the hotel

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#164]
left on accident trying to turn off the teleporter, couldn't return because the teleporter was blocked, got gibbed by an admin for my trouble

**Comment by WallaceShark** [comment]
Exile implants on hotel staff please. Flavortext holds no binding on a light RP server.

**Comment by cacogen** [comment]
if exile implants just kill people when they leave that doesn't fix the problem of people accidentally walking into or being pushed into the teleporter

should stop them entering entirely as though they were carrying the disk

edit: looking at the code, they seem to work this way for the gateway but i don't know if the teleporter looks for them

**Comment by tortellinitony** [comment]
Solved
