### ISSUE TITLE
no spam limit on ooc or ic messages

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#165]
![](https://puu.sh/tZkWB/333fd10358.png)
probably should limit message length and frequency to something more manageable

_edit:_

![](https://puu.sh/tZly1/3b414bac59.png)
should probably do it for ic too

**Comment by JohnGinnane** [comment]
@JamieH thoughts on adding a new value to config; OOC character limit (default 300)

Or we could just OOC ban people spamming..

**Comment by tortellinitony** [comment]
yea the thing with this kind of stuff is it's easy to just ooc ban that person or mute their IC

**Comment by j-mie** [comment]
Yeah, I suggest we leave it as is and get people to mute OOC for the spammer.

**Comment by cacogen** [comment]
Yeah, that's what I expected would happen but there were like three admins online and it didn't. Seems like a better idea to save them having to mute someone in the first place. What if there are no admins?

Is there a need for messages to be that long? Nobody ever writes anything that length. It just gets used to spam.

I already made a fix last night for spam with this and other things, so I'm just going to PR it and see what happens.

**Comment by cacogen** [comment]
i'm gonna close this
