### ISSUE TITLE
Dufflebags affect movement

### ISSUE THREAD

**Issue by Jsau7** [HippieStationArchive/HippieStation13-2#187]
I figured out why my movement speed has been somewhat slower than usual lately, Wearing Dufflebags on your back makes your movement speed slower than wearing a normal backpack.

**Comment by Spacedong** [comment]
it does

**Comment by cacogen** [comment]
it's intended

**Comment by tortellinitony** [comment]
Dufflebags can store more, so this is the drawback. Not an issue.
