### ISSUE TITLE
timers dont make any sound

### ISSUE THREAD

**Issue by gumner** [HippieStationArchive/HippieStation13-2#195]
how can i fake terrorism now

**Comment by TDcoolguy300** [comment]
Make the sound with your mouth.

**Comment by KittyKathy** [comment]
This is good because before you could not use them at all for a actual bomb only memes. Everyone runs when they hear a timer no point in using them other than for pranks. There should be a option to toggle it to make noise or be silent.

**Comment by PopNotes** [comment]
I'm gonna mindlessly regurgitate what Kitty said here. I'll sacrifice a lamb in my front yard so the coders may once again work their magic for a "beep on/off" button on timers.

**Comment by cacogen** [comment]
yeah that's good do that
