### ISSUE TITLE
Mapping Error? Stick figure icons? Also Space Parallax?

### ISSUE THREAD

**Issue by KittyKathy** [HippieStationArchive/HippieStation13-2#197]
Not sure if this is intended or not but I don't think it is.
![error](https://cloud.githubusercontent.com/assets/24830804/22918959/1bb18e32-f25b-11e6-8222-f2fe1458a6cd.png)
Those two windows blew my character are blocking a entrance/exit to speakeasy.
I think this may be a error correct me If I am wrong.
Pre-Rebase look
![pre-rebase speakeasy](https://cloud.githubusercontent.com/assets/24830804/22920229/f5b10e0e-f261-11e6-8b93-5e67868a6190.png)
New-Rebase look
![new-rebase speakeasy](https://cloud.githubusercontent.com/assets/24830804/22920245/0ef99cf0-f262-11e6-9df8-ca9ade62976c.png)

Also do you see that adrenal icon in my hud on the fist picture it's literally a stick figure with a green arrow like really there was no other icon to use like a stimpack medipen?

Yeah my space parallax is broken for me it flickers between off and on then most of them time just shows nothing like the space tile was replaced by a black tile or does the top part only as black tiles. Turning it off is worse as it makes all the tiles dark like they were space or they make them dark with the original icon as a frame around it. That last part  only happens in certain areas and this does not happen when I was a ghost though.
Example
![weird](https://cloud.githubusercontent.com/assets/24830804/22920596/d712aece-f263-11e6-942d-5458da6a9293.png)
Maybe this has to do with the lighting mixing with space parallax or just my directx is outdated or something not sure, minor inconvenience really.
Yeah I am on Byond 511.1373 beat and have that direct x sdk thing you guys said to download.

**Comment by cacogen** [comment]
you should probably do three separate issues

**Comment by ghost** [comment]
> Yeah my space parallax is broken for me it flickers between off and on then most of them time just shows nothing like the space tile was replaced by a black tile or does the top part only as black tiles. Turning it off is worse as it makes all the tiles dark like they were space or they make them dark with the original icon as a frame around it. That last part only happens in certain areas and this does not happen when I was a ghost though.

Please report this issue over at https://github.com/tgstation/tgstation as we have not modified anything related to that

**Comment by PopNotes** [comment]
The icon is how it should be. It's just that shitty.

**Comment by KayeArray** [comment]
Adrenal icon is a thing of beauty, also can confirm space parallax is glitchy as fuck.

**Comment by JohnGinnane** [comment]
The mapping issue is real, perhaps @KittyKathy you might create issue for that specifically?
