### ISSUE TITLE
Pictures and books show up as invisible in pictures

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#200]
![image](https://cloud.githubusercontent.com/assets/4482206/22940957/a6f18c4e-f2b1-11e6-977b-2ec95a2fdac3.png)

I would guess because they have don't have a definite appearance all the time but I'm honestly not too sure.

**Comment by ghost** [comment]
Related to https://github.com/tgstation/tgstation/issues/23184

**Comment by Chnkr** [comment]
Please test this on /tg/station and let us know if it happens there as well, if it does please open an issue over at https://github.com/tgstation/tgstation

**Comment by cacogen** [comment]
these have been bugged for years and years

**Comment by ghost** [comment]
Fixed via #426
