### ISSUE TITLE
Alternate Emergency Shuttles Are Broken

### ISSUE THREAD

**Issue by WallaceShark** [HippieStationArchive/HippieStation13-2#205]
ADMIN LOG: load_template(): Shuttle Template _maps/shuttles/emergency_bar.dmm has no	 mobile docking port. Aborting import.

All of the shuttles are like this. It is now impossible to change the emergency shuttle, both from admin side and buying new shuttles as the captain. This is a problem from the most recent build.

**Comment by ghost** [comment]
@JamieH did you touch something?

**Comment by j-mie** [comment]
All fixed. Reopen if you encounter this again.
