### ISSUE TITLE
Lavaland Boats

### ISSUE THREAD

**Issue by kaptem** [HippieStationArchive/HippieStation13-2#228]
Lavaland boats don't work, when you make a boat and push it onto lava and get on said boat, and proceed to try to use your oar, either by clicking on lava (which does nothing) or trying to move normally you just step into lava.

**Comment by ghost** [comment]
Please test this on /tg/station and let us know if it happens there as well, if it does please open an issue over at https://github.com/tgstation/tgstation

**Comment by ghost** [comment]
This should have been resolved, please test this again and open a new issue if this is still an issue
