### ISSUE TITLE
[GAMEBREAKING] [SHUT IT DOWN] Lawn mower description has a typo

### ISSUE THREAD

**Issue by myontasm** [HippieStationArchive/HippieStation13-2#231]
![gamebreaking](https://cloud.githubusercontent.com/assets/10575508/23068140/b2f06740-f522-11e6-8f4d-53136746e4a4.png)

Literally unplayable, who did this 😂😂😂😂😂

**Comment by ghost** [comment]
I'll fix it 😂

**Comment by JohnGinnane** [comment]
Fixed in #396

**Comment by cacogen** [comment]
no it just got changed to a different spelling mistake
