### ISSUE TITLE
verbs not working after being bombed (me, ahelp, say)

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#247]
In-Game report from direvictory:
Revision info: Server revision 9b2fb7e7eaf97bb09192346904efe7462a0132c3 compiled on: 2017-02-18

>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
got bombed in shuttle, got defibbed, couldn't use the verbs.

>What you expected to happen
being able to use the verbs

>What actually happened
wasn't able to use them,had to reconnect

>Steps to reproduce if possible

get bombed then defibbed, i think

**Comment by tortellinitony** [comment]
Not specific enough, not confirmed or replicated

**Comment by Pyko1** [comment]
Sounds like some odd glitch with being deaf, dying and getting defibbed back to life tho.
