### ISSUE TITLE
Implanted Legion Soul does not heal

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#257]
In-Game report from aiia:
Revision info: Server revision 0000000000000000000000000000000000000000 compiled on: 2017-02-18

>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Surgically implanting a Legion Soul into your chest does not heal you periodically.

>What you expected to happen
The soul should be able to slowly heal you over time if surgically implanted into your chest.

>What actually happened
Legion Soul does not heal at all when implanted in your chest.

>Steps to reproduce if possible
1. Kill a Legion
2. Grab it's soul and implant it into your chest.
3. Punch/damage yourself.

**Comment by KittyKathy** [comment]
This was changed it no longer provides a passive heal it instead grants a action button that fully heals you as if you used the soul on yourself. the soul also self activates when you hit crit healing you back to full health like a second chance.

**Comment by tortellinitony** [comment]
Not an issue, use it in hand for the healing power.
