### ISSUE TITLE
Mecha race in character creation makes the player's skin invisible.

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#259]
In-Game report from mchatters:
Revision info: Server revision dc9d53ae76738c0b6b138846b52d8417c92d1ee7 compiled on: 2017-02-18

>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
People who select the mecha species in character creation have their skin turn invisible.

http://image.prntscr.com/image/6b97054e6f5c45598b009799c337c87f.png

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by cacogen** [comment]
you can't click the invisible parts either, so presumably you can take off your clothes and be nearly unclickable
