### ISSUE TITLE
security cyborg module change animation stuck in infinite loop

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#260]
![](https://puu.sh/u9hO4/e0de63fcdd.gif)

you can't move while like this either

please test code more thoroughly before committing or merging

#173 
#11

**Comment by JohnGinnane** [comment]
i did :(

**Comment by ghost** [comment]
fucking lmao

**Comment by tortellinitony** [comment]
Should have been fixed in an earlier revert.
