### ISSUE TITLE
brig timer access requirement doesn't work

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#268]
brig timers are meant to ![require access](https://github.com/HippieStation/HippieStation13/blob/master/code/game/machinery/doors/brigdoors.dm#L26) to use, but for some reason they don't. i think the req_access check was accidentally removed after the interface was updated to tgui.

**Comment by ghost** [comment]
yes,same problem here

**Comment by cacogen** [comment]
wew
