### ISSUE TITLE
Faster Doors

### ISSUE THREAD

**Issue by j-mie** [HippieStationArchive/HippieStation13-2#27]
I think we had faster doors before?

**Comment by JohnGinnane** [comment]
Current code: https://github.com/HippieStation/HippieStation13/blob/master/code/game/machinery/doors/door.dm#L228

Old code: https://github.com/HippieStationCode/HippieStation13/blob/56a3fdddeb58b6e0dedb20514f4cc43bee628c58/code/game/machinery/doors/door.dm#L196

Looks to be the exact same

**Comment by j-mie** [comment]
The animations were faster, I remember doing that my self. Meh - people aren't complaining for now.
