### ISSUE TITLE
Augmentations

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#270]
In-Game report from machinimal:
Revision info: Server revision 0000000000000000000000000000000000000000 compiled on: 2017-02-18

>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Augmenting certain lizard heads makes them invisible

>What you expected to happen
Be able to see my head

>What actually happened
I couldn't see my head

>Steps to reproduce if possible

Augment your head as a lizard (Round and light snout)

**Comment by tortellinitony** [comment]
This should have been fixed.
