### ISSUE TITLE
Changeling Hallucination sting sometimes crashes dreamseeker

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#284]
In-Game report from mechknight:
Revision info: Server revision 0000000000000000000000000000000000000000 compiled on: 2017-02-19

>General description of the issue
The hallucination sting will occasionally crash the game. Probably related to the mindbreaker crashing bug. 

>Steps to reproduce if possible
Get stung by a changeling

**Comment by tortellinitony** [comment]
Appears to be all hallucination.

Perhaps mentioned in https://github.com/tgstation/tgstation/issues/22565

**Comment by tortellinitony** [comment]
Already in #181.
