### ISSUE TITLE
Out of line APC just below clown/mime office. 

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStationArchive/HippieStation13-2#29]
![oh dear](https://cloud.githubusercontent.com/assets/22083966/22634795/9a33be4c-ec25-11e6-979d-9a4034629d0c.PNG)

Pic says it all.

**Comment by ghost** [comment]
HE'S A LOOSE CANNON, CANT HAVE HIM ON THE FORCE ANY LONGER, HE'S TOO OUTTA LINE

**Comment by Spacedong** [comment]
LMAO

**Comment by Pyko1** [comment]
fixed
