### ISSUE TITLE
Bottles do not visually show their fill level

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#295]
In-Game report from vexingraven:
Revision info: Server revision 0000000000000000000000000000000000000000 compiled on: 2017-02-20

>Revision (Should be above if you're viewing this from ingame!)
I can't find it, but the current version as of 2/20/2017

>General description of the issue
Bottles do not visually deplete and empty like they used to. I believe this started after one of the fixes that went in today that was supposed to fix the lag, the same one that made playes start the round invisible went it first went through.

>What you expected to happen
When filling and emptying a bottle its sprite should visually show this fill level. When emptied it should turn into a completely empty bottle. Similar to how beakers do.

>What actually happened
When emptying a bottle, its sprite does not update at all.

>Steps to reproduce if possible
Fill a bottle, empty a bottle. Easiest as a chemist.

**Comment by KittyKathy** [comment]
Some bottles use static sprites that never change but I assume he is talking about the ones that the chem machine makes which do update sprites not sure what is causing that.

**Comment by JohnMcLaime** [comment]
Same with new fuel/water tank sprites, they dont have the ~ ammount visible without examining it.
I dont get why they decided to change sprites to lower quality ones, visually (they really look low quality compared to hippie prebase ones) and technically (?) since you cant heat reagents and cant repair destroyed tanks.

**Comment by cacogen** [comment]
are hippie prerebase ones the ones we're currently using? because those are newer sprites than /tg/ runs

also botany bottles have needed updating to match the chemistry ones for awhile, i've been wanting to do it for ages but have never gotten around to it

**Comment by msgerbs** [comment]
The ones I tested with were the chemistry bottle sprites but IIRC this used to work for the pre-spawned ones too (such as the epinephrine bottle that spawns in Chemistry at round-start). I am unsure if it used to work for the vending machine bottles such as the anti-toxin bottles.
