### ISSUE TITLE
old shit

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#297]
In-Game report from captainruddy:
Revision info: Server revision 0000000000000000000000000000000000000000 compiled on: 2017-02-20

>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
BIRNG BACK THE OLD HANGING MAN.... and the music... it was awesome

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by tortellinitony** [comment]
I don't think we're gonna bring back the old music and lobby icon. Not really an issue either
