### ISSUE TITLE
Invincible blob spores

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#325]
In-Game report from bardofrage:
Revision info: Server revision 0000000000000000000000000000000000000000 compiled on: 2017-02-21

>General description of the issue

Instead of "Fragile" blob spores dying they just stop moving and get in the way
>What you expected to happen
For the blob spore to die

>What actually happened
It survived

>Steps to reproduce if possible
Play a blob and make fragile spores

**Comment by KittyKathy** [comment]
Yes this is confirmed and a annoying bug merge this pull from upstream to fix it. https://github.com/tgstation/tgstation/pull/24377

**Comment by tortellinitony** [comment]
Shoulda been fixed
