### ISSUE TITLE
I have no words.

### ISSUE THREAD

**Issue by j-mie** [HippieStationArchive/HippieStation13-2#33]
Okay so basically WallaceShark had an event on and used the expensive shuttle (`Luxury Shuttle`) - A crew member then changed it to (`Asteroid With Engines Strapped To It`) this was then changed back to the `Luxury Shuttle` but the shuttle still landed in the wrong place. 10/10.

**Comment by WallaceShark** [comment]
Welding fuel can't melt steel memes.

Blacklist that meteor shuttle yo.

**Comment by j-mie** [comment]
Done.

**Comment by GuyonBroadway** [comment]
The meteor shuttle is a barrel of laughs and should stay or at the very least add it to emag functionality.

**Comment by Kierany9** [comment]
>Asteroid With Engines Strapped To It

based tg

**Comment by tortellinitony** [comment]
we could disable the asteroid shuttle since it is just a meme that kills people

**Comment by GuyonBroadway** [comment]
It's a bit of fun for antags who get their hands on a command level ID. Hide it behind the emag and perhaps add a couple more _fun_ shuttles for when you emag the console. 

As it stands that bug sounds hilarious as fuck and I wish I was there to see it.

**Comment by j-mie** [comment]
I feel like it's too powerful as an antag thing, maybe 30 seconds before it lands we could sound out some kind of warning, I dunno - for now it's blacklisted.

**Comment by ghost** [comment]
**_H U G B O X_**

**Comment by yobob591** [comment]
Asteroid shuttle is an absolute meme pls readd as an emag feature

**Comment by WallaceShark** [comment]
I actually gotta agree. It would make a hella good emag function.

**Comment by Kierany9** [comment]
>tg fights tooth and nail to not let people remove the memeshuttle due to it causing admin headaches

>it gets removed immediately on hippie

but _why_

**Comment by Spacedong** [comment]
asteroid is good what da fuck

**Comment by WallaceShark** [comment]
Wallace is salty that his shuttle event got turned into a 9/11 simulator cause of asteroid shuttle.

**Comment by KittyKathy** [comment]
There is a warning whenever a shuttle is landing it makes the tiles where it will land have some blue overlay circle thing and in the status panel it shows what the shuttle is so people can't be like I had no way of knowing what shuttle it is or where it would land. Yeah a announcement  30 seconds before it lands that the meteor shuttle is going to land and where would be nice with the feature with it being disabled with a emag.

**Comment by tortellinitony** [comment]
So what I gather is how to fix the meteor shuttle:
- Emag only
- Once you choose it, you cannot switch your choice

**Comment by yobob591** [comment]
better idea, make it so asteroid shittle is a legit shuttle, but when the comms console is emagged the shuttle crashes into the station no matter what kind it is (well unless it's a build a shuttle of course)
