### ISSUE TITLE
weird bug with tgui windows constantly losing focus

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#346]
![](https://puu.sh/uhNHy/d2475fa9fb.gif)

not sure what the cause of this is, only that it happened after i had brain damage (which prevents you using computers) and hallucinations. i was no longer hallucinating or retarded when using this.

this happened when i tried to use other tgui windows (the condimaster) as well

**Comment by JohnGinnane** [comment]
If you start a game not retarded and use chem dispenser does it happen? Or only after being retarded (and having it cured)?

**Comment by PopNotes** [comment]
You were still retarded. Mannitol takes a bit of time to work.

**Comment by cacogen** [comment]
yeah, you're right. 

i'm not visibly or audibly retarded and brain damage doesn't show up on health scanners for some reason. but according to an admin i have 60 brain damage.

**Comment by GuyonBroadway** [comment]
Yeah, sometimes mannitol takes fucking ages to work. But the computer loosing focus like that is intentional iirc so as to make it possible yet tricky to make mannitol while tarded.
