### ISSUE TITLE
cryo is garbo

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#35]
1. you can't turn it on yourself anymore
2. if you jump in hoping it'll turn on automatically you can't just jump out, you have to wait 30 secs to eject
3. cryo tube doors can be set to manual operation for some dumb reason (and that seems to be the default setting) meaning when cryo is finished you aren't automatically ejected. either someone has to open the door for you, or you have to wait to wake up and then go through the manual ejection sequence.

i don't know why [/tg/ did this](https://github.com/tgstation/tgstation/pull/13321). they seem to have had a war on medbay for years, making it tedious and needlessly complicated.

**Comment by JohnGinnane** [comment]
Thank you for linking the PR, that should make it easy to revert this. I wonder if we can revert these changes alone or whether it needs to be done manually
