### ISSUE TITLE
Loyalty implanted people can still be antags

### ISSUE THREAD

**Issue by KittyKathy** [HippieStationArchive/HippieStation13-2#36]
Well I noticed there were like two rounds where we had a round start traitor as a captain. I checked the code and it looked right the only thing that it could possibly be is the config. Is the config files on the git the ones used for the actual server?

This is the problem right here I think.
https://github.com/HippieStation/HippieStation13-rebase/blob/master/config/game_options.txt#L221
I think you need to uncomment #PROTECT_ROLES_FROM_ANTAGONIST so loyalty implanted people don't end up as most antagonist.

**Comment by JohnGinnane** [comment]
@JamieH will need to fix this if it's config issue as the ones in the repo are placeholder ones you copy into parent folder

**Comment by j-mie** [comment]
Fixed. Thanks for that.

**Comment by j-mie** [comment]
We modified this config on the server but are still getting reports of this?
