### ISSUE TITLE
gatfruit won't turn into revolver when used inhand

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#366]
In-Game report from direvictory:
Revision info: Server revision 98a9f27f71274d006c6738a8103c495be5fa813f compiled on: 2017-02-26

>General description of the issue
I was a plantman in the lifebringer ruin at lavaland, planted a gatfruit, when I harvested it, I tried to use it inhand, and nothing happened.

>What you expected to happen
I expected to get a revolver upon inhand use.

>What actually happened

I didn't. the gatfruit just disappeared.
>Steps to reproduce if possible

**Comment by Carbonhell** [comment]
what?you need to eat it

**Comment by cacogen** [comment]
#367
