### ISSUE TITLE
[Botany] Harvests don't work

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#367]
In-Game report from lordquailius:
Revision info: Server revision 98a9f27f71274d006c6738a8103c495be5fa813f compiled on: 2017-02-26

>General description of the issue
Plants like the Egg-plant and gatfruit don't work properly

>What you expected to happen
Use the egg-plant fruit or gatfruit fruit in the hand to get an egg or a gun(I believe?)respectively.

>What actually happened
The fruit disappears and you get nothing.

>Steps to reproduce if possible

Grow Egg-plant or gatfruit and try to use the grown fruit in hand.

**Comment by cacogen** [comment]
https://github.com/tgstation/tgstation/issues/24434
https://github.com/tgstation/tgstation/pull/24469

**Comment by tortellinitony** [comment]
Did you try eating it? The gun is listed as trash so it should appear if you EAT IT.

Yes, confirmed. There DOES appear to be an issue where using it in hand makes the item disappear. Still, EATING The item will make the gun or egg pop out as intended.
