### ISSUE TITLE
/tg/PRs we have to add!

### ISSUE THREAD

**Issue by tortellinitony** [HippieStationArchive/HippieStation13-2#37]
- [ ] https://github.com/tgstation/tgstation/pull/23697

- [ ] https://github.com/tgstation/tgstation/pull/23662

- [ ] https://github.com/tgstation/tgstation/pull/23618

- [ ] https://github.com/tgstation/tgstation/pull/23758

There are definitely more. Look for major fixes.

**Comment by ghost** [comment]
Just add the github repo as a upstream origin, then fetch it and merge it.
Then remove all the stupid shit and put it in a PR.

No need to manually merge each PR

**Comment by j-mie** [comment]
- [ ] https://github.com/tgstation/tgstation/pull/23694

**Comment by tortellinitony** [comment]
I'll add this to mine..
