### ISSUE TITLE
everything in space turning invisible

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#38]
first noticed this on centcom when i was picked as ert (and later deathsquad). everything was invisible (all i saw was space) until i was brought to the station by an admin. interestingly, this didn't happen while observing. only while playing a mob.

at first i assumed it was a feature where player mobs can't see centcom presumably to prevent people glitching into it and stealing things. but then i encountered it again while entering the shitty area of the luxury shuttle in escape at the end of a different round.

i'm running BYOND 510 because I was having unrelated problems with 511.

**Comment by Pyko1** [comment]
You sure it wasn't just mesons and no light?

**Comment by cacogen** [comment]
definitely

i didn't have mesons as the ert and boarding the shuttle i had secHUDs

here is me as an ert at the ert spawnpoint:
![](https://puu.sh/tR0Pg/3568cc2c07.png)

here's me on the shuttle after launch:
![](https://puu.sh/tR1ax/9455dac201.png)

right-clicking shows the contents of tiles in the context menu like normal

**Comment by j-mie** [comment]
Try deleting your BYOND cache

**Comment by ghost** [comment]
Upgrade to byond 511

**Comment by j-mie** [comment]
I'm on 510.1347 and not having this issue. I think TGUI is having issues with 511 too.

**Comment by j-mie** [comment]
Try this *very* specific version of BYOND 511: http://www.byond.com/download/build/511/511.1370_byond.exe

**Comment by tortellinitony** [comment]
TGUI is having issues with the latest version of 511. I restored mine to .165 I believe, and it works fine right now.

**Comment by MrsTonedOne** [comment]
Install the directx SDK https://www.microsoft.com/en-us/download/details.aspx?id=6812

(oh, and run a 511 version after 511.1662, 511.1670 is the current best version www.byond.com/download/build)

**Comment by MrsTonedOne** [comment]
Another trick is to just disable parallax in game preferences

**Comment by Spacedong** [comment]
so is this actually an issue or just clientside?

**Comment by MrsTonedOne** [comment]
client side/byond issue

**Comment by cacogen** [comment]
centcom and the shuttle seem to be fine now having switched to that version of byond (511.1370, not .1670). haven't had an opportunity to test it on the luxury shuttle or the ert spawn so i don't know for sure yet though.

installing that version of BYOND also fixed the problems I was having with TGUI having no stylesheet (just appearing black and white).
