### ISSUE TITLE
character setup preview bug, black image

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#381]
In-Game report from direvictory:
Revision info: Server revision bc0502d97f23d9ffa3a60989e7e58cbac3ef53ac compiled on: 2017-03-01

>General description of the issue
sometimes, in the character setup screen, instead of viewing a preview of your character, the char image is completely black

>What you expected to happen
for it to not be black and be seeable

>What actually happened
totally black and not being able to see it

>Steps to reproduce if possible
I think making hair completely black makes it happen

**Comment by JohnGinnane** [comment]
I've had this happen too, however I ignore it and continue setting up my character and eventually they reappear (usually around the backpack type and eyes/hair section)

**Comment by ghost** [comment]
yeah its caused by the overlay queue stuff, need to pull some fixes from tg

**Comment by tortellinitony** [comment]
It's the subsystem not loading yet. This should be fixed if we update, but either way it's not a bug.
