### ISSUE TITLE
Ling Regenerate does not work

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#384]
In-Game report from urikhunt:
Revision info: Server revision bc0502d97f23d9ffa3a60989e7e58cbac3ef53ac compiled on: 2017-03-01

>General description of the issue
Regenerate for Ling does not work

>What you expected to happen
To heal brute/burn damage

>What actually happened
Nothing

>Steps to reproduce if possible
Click regenerate as a Ling and see it do nothing

**Comment by tortellinitony** [comment]
desc = "Allows us to regrow and restore missing external limbs, and \
		vital internal organs, as well as removing shrapnel and restoring \
		blood volume."

Not an issue.
