### ISSUE TITLE
bottom half of screen freezes when shuttle arrives

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#385]
In-Game report from urikhunt:
Revision info: Server revision bc0502d97f23d9ffa3a60989e7e58cbac3ef53ac compiled on: 2017-03-01

>General description of the issue
bottom half of screen freezes when shuttle arrives, doesn't go away after closing and restarting game

>What you expected to happen
not to freeze half of the gaming screen

>What actually happened
bottom half of gaming screen froze, can still move around but top half of screen is choppy.

>Steps to reproduce if possible
call shuttle

**Comment by tortellinitony** [comment]
Not enough info to go off of. Sounds like a client issue, but if you can provide screenshots you may reopen this.
