### ISSUE TITLE
Character Setup

### ISSUE THREAD

**Issue by Nokington** [HippieStationArchive/HippieStation13-2#39]
I can't change hair style or hair color anymore what is this.
http://puu.sh/tQZGJ/85d110b67a.png
I also tried updating byond, clearing cache and going back to 510.

**Comment by Spacedong** [comment]
worked for me, can anyone confirm

**Comment by tortellinitony** [comment]
Works for me. Go to the right version of byond

**Comment by Nokington** [comment]
I had uninstalled and gone to 510 and 511 twice and it didn't work for me.

**Comment by Nokington** [comment]
its working now that I can change my race. so rip in rip

**Comment by JohnGinnane** [comment]
How'd you fix it?

**Comment by Nokington** [comment]
Well once the server updated to allow me to change my race it started working again. That is what I assume fixed it
