### ISSUE TITLE
Port back self-cryo

### ISSUE THREAD

**Issue by Arzion5** [HippieStationArchive/HippieStation13-2#406]
Being able to cryo self automatically by closing the door wasn't ported back. It should be.

**Comment by JohnGinnane** [comment]
Yes

**Comment by tortellinitony** [comment]
This is not a bug, and actually it is the opposite of a bug since the variable did not reset when cryo was opened or closed..

**Comment by Spacedong** [comment]
gonna fiks dis

**Comment by JohnGinnane** [comment]
Whoops

**Comment by JohnGinnane** [comment]
Actually, technically a bug from what I can see:

https://github.com/HippieStationCode/HippieStation13/blob/56a3fdddeb58b6e0dedb20514f4cc43bee628c58/code/ATMOSPHERICS/components/unary_devices/cryo.dm#L209
