### ISSUE TITLE
start of round music

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#408]
In-Game report from captainruddy:
Revision info: Server revision 58f1e1d07922a9c8ca18d6b7142aebee061c3f22 compiled on: 2017-03-04

>General description of the issue
its shit

>What you expected to happen
change it to macintosh plus. thanks

>What actually happened

>Steps to reproduce if possible

**Comment by PopNotes** [comment]
**fuck**

**Comment by cacogen** [comment]
the loop's too short, it's really annoying
