### ISSUE TITLE
Photos don't show monkeys

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStationArchive/HippieStation13-2#409]
![image](https://cloud.githubusercontent.com/assets/3355198/23589513/798ea556-01c6-11e7-807c-1cebb80244b8.png)

![image](https://cloud.githubusercontent.com/assets/3355198/23589517/877fc942-01c6-11e7-883a-3adcf58fab02.png)

**Comment by JohnGinnane** [comment]
![image](https://cloud.githubusercontent.com/assets/3355198/23589534/cf88e5ca-01c6-11e7-8892-8ff4cbbaddf8.png)

![image](https://cloud.githubusercontent.com/assets/3355198/23589536/d3d41456-01c6-11e7-9096-08ebe93b79eb.png)

**Comment by PopNotes** [comment]
working as intended :^)

**Comment by ghost** [comment]
`getflaticon` is a shitstain

**Comment by cacogen** [comment]
photos have been bugged forever (like 5+ years)

**Comment by Spacedong** [comment]
really makes you think
