### ISSUE TITLE
Chameleon items broken

### ISSUE THREAD

**Issue by KittyKathy** [HippieStationArchive/HippieStation13-2#421]
Well pretty much all the chameleon items like thermals and the chameleon  kit are broken. When you press the hud icon to change the look it does nothing so it's stuck in the default state. Probably caused by this pr #403.

**Comment by JohnGinnane** [comment]
Aw shit

**Comment by JohnGinnane** [comment]
Okay gonna have a look later today. Should we revert?

**Comment by tortellinitony** [comment]
`proc name: initialize disguises (/datum/action/item_action/chameleon/change/proc/initialize_disguises)
src: Chameleon Change (/datum/action/item_action/chameleon/change)
call stack:
Chameleon Change (/datum/action/item_action/chameleon/change): initialize disguises()
PDA (/obj/item/device/pda/chameleon): New()
the PDA painter (/obj/machinery/pdapainter): New(the floor (102,121,1) (/turf/open/floor/plasteel/blue/side))`

The above runtime happens related to chameleon huds when initialize_disguises is called.

**Comment by JohnGinnane** [comment]
Interesting
