### ISSUE TITLE
weird bug with ruin spawner

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#435]
i'm assuming this is a bug and not some next level meta corruption ruin i'm not aware of

![](https://puu.sh/uA3oS/bb3ee34340.png)

**Comment by ghost** [comment]
lmao what

**Comment by ghost** [comment]
dude nice

**Comment by Spacedong** [comment]
NICE

**Comment by Pyko1** [comment]
interesting i wonder what caused it fire multiple times in same spot.

**Comment by tortellinitony** [comment]
this was the doing of a spank monkey
