### ISSUE TITLE
Add a "super electronic magnetic device"

### ISSUE THREAD

**Issue by Arzion5** [HippieStationArchive/HippieStation13-2#46]
A super emag would be able to emag a massive amount of things compared to the regular emag, but costs 16 TC.

-Emagging vendors also hacks them along with unlocking their access
-Emagging a crew monitoring console or a handheld version shows the location of every crewmember, ignoring the jumpsuit's sensor settings. Does not work on jumpsuits with no actual sensors.
-Emagging a recharger/Mech recharger/robot recharger causes them to drain power cells instead of recharging.
-Emagging the security console can show camera view from every single existing camera, including Centcomm cameras
-Emagging the security records console sets everyone on wanted automatically
-Emagging a medical records console sets everyone to "insane" (it may or may not affect bots, actually)
-Emagging a food processor allows it to function as a gibber that can gib humans
-Emagging energy weapons overloads them, causing to explode after a short amount of time
-Emagging an explosive makes it blow up instantly
-Emagging an ID console allows it to grant Syndicate access. Can be reset.
-Emagging a station-bounced radio allows it to make every voice going through it to be in big text, as if using the high-volume function on a command headset
-Emagging station alert consoles makes them automatically end every alarm, but cannot be emagged again for 30 seconds
-Emagging the stock exchange computer allows for more favorable or unfavorable outcomes (comes with a setting). Space magic indeed.
-Emagging a PDA painter allows for a blood-red syndicate PDA skin
-Emagging a flash allows you to AoE stun with them or pass through eye protections if used individually, but can be used only once in this state.
-Emagging mindshield implants turns them into greater mindslave implants. Way to save up on costs!
-Emagging a teleporter beacon makes all teleports redirect to it for a short amount of time, including random hand-tele teleports and reactive armor teleports.
-Emagging a suit storage unit causes it to explode upon next use. Useful for gibbing bodies.
-Emagging a chem master allows unrestricted amount of units into patches or pills.
-Emagging a changeling sting causes the person to experience any of the effects of an actual changeling's sting excluding transformation. You can get dull armblade'd, cryostinged, and more!
-Emagging an all-in-one grinder makes it able to grind any object. Resulting chemical is named into "Unknown Sludge", slightly toxic.
-Emagging an ice cream vat poisons the ice creams.
-Emagging a food cart injects 10 units of a random poison (including nanites) into the food stuff.
-Emagging a camera allows it to function as a flash if used close on a person
-Emagging a crematorium causes plasma and fire to vent from it upon use.
-Emagging a morgue locks it and always makes it show up as red, despite the actual status of the victims. Can only be unlocked from the outside or after a 30 second duration
-Emagging a tachyon-doppler array causes it to produce explosive sounds and send over the reports on radio. Useful for confusion.
-Emagging a cloning console (not the cloner) causes the cloned people to have random disabilities.
-Emagging a cryo cell will mess up with the interface, causing health to be registered as damage and the inserted beakers to be shown as random poisons.
-Emagging a teleporter console will always make it remain uncalibrated. "Why is the Captain a fly?"
-Emagging a gravity generator imposes a slowdown on everyone by increasing gravity. Can be reset.
-Emagging a pAI allows for additional syndicate functions, like drug-injections, acting as a flash, and making door hacks 20x faster and silent.
-Emagging a slime management console can allow slimes to be placed outside of Xenobiology. Now you can laugh maniacally
-Emagging a bag of holding causes it to turn unstable, allowing it to carry an actual infinite amount of items of any size, but will turn into a singuloth after a minute
-Emagging a chainsword (even the sacred one) causes it to have an almost guaranteed chance to delimb and bypass armor, but it causes a massively loud sound and the victim to emote a scream
-Emagging a hardsuit, either on yourself or on another person, causes it to be permanently stuck, only being able to be taken off via surgery or massive damage
-Emagging a spell wand causes it to be self-recharging (Pretty much cannot be done outside of admin intervention or real fucky round-type conversion, or traitor minering)
-Emagging a spell book causes it to turn into another type of spellbook, but only once. Heretics beware, the chaplain has fireball.

**Comment by ghost** [comment]
this sounds OP

**Comment by ArcLumin** [comment]
This is not the place to ask for features


...is what I would say, but we have a new host, so new rules. So hey. Maybe it is

**Comment by Sarcalogo** [comment]
This isn't an issue lol. Issues are for big fixes and I guess since it's a rebase, requests to PORT already existing old code.

**Comment by Spacedong** [comment]
shut the fuck up nigger

**Comment by yobob591** [comment]
I like but making bag of holding become a singulo after one minute just to have it hold infinite shit is useless and suicidal

**Comment by Arzion5** [comment]
The choice of the item and/or effects to be incorporated into the game are at the admins' discretions, but you are right. I originally thought about it as something along the lines of "put everything in a bag and it's gone forever", but it could be modified to just turn into a singularity after 10 seconds.

**Comment by yobob591** [comment]
I think just having an infinite storage bag is better since having more ways to turn the bag f holding into a singulo is useless as it's not hard to get more than one

**Comment by Arzion5** [comment]
As fun as that would be, it would considerably ruin the game extremely easy and even cause issues if you can just have every item handy for every situation

**Comment by yobob591** [comment]
Reminder that the emag costs almost all of your TC and then you still have to spend almost half the round researching for bags of holding

**Comment by PopNotes** [comment]
The Emag is ridiculously good as it is. It's really a bad idea to NOT buy one when you get traitor, as it pretty much benefits every playstyle.

**Comment by j-mie** [comment]
This is dumb.
