### ISSUE TITLE
Races Not Selectable in Setup Character

### ISSUE THREAD

**Issue by WallaceShark** [HippieStationArchive/HippieStation13-2#47]
It seems that hippie race code is neither ported nor available at character start. I'm getting a lot of complaints from players about not being able to skeleton and moth.

Can we port those in soon?

**Comment by tortellinitony** [comment]
you can be a skeleton and tarajan iirc

**Comment by JohnGinnane** [comment]
I think we need to update it to be spooky skellington, and add in moth and lizard people

**Comment by WallaceShark** [comment]
They aren't selectable at roundstart, and have their associated race bonuses.

**Comment by Spacedong** [comment]
intended, fuck snowflakes

**Comment by jediluke1999** [comment]
Moths, please.
