### ISSUE TITLE
Dufflebag Encumbrance

### ISSUE THREAD

**Issue by dwright92** [HippieStationArchive/HippieStation13-2#62]
Dufflebags have been and should continue to be a cosmetic choice. In prior versions of Hippie Station, they have been used just like any satchel or backpack. This needs to return, as Encumbrance of dufflebags is shitty as fuck, to put it unprofessionally. 

Some argue, "WELL THEY HAVE EXTRA SPACE SO THEY SHOULD HAVE A TRADE OFF"

My counter argument is, "Well then remove the extra space." Or don't. If you want to keep it and have that esoteric bit of knowledge that dufflebags are the definitive bag of choice, go ahead. 

Either way, FREE DUFFLEBAGS 2017

**Comment by tortellinitony** [comment]
I believe it was decided that dufflebags have a benefit, so this is the tradeoff, and there may be a cosmetic dufflebag added in the future with no benefits or tradeoffs.
