### ISSUE TITLE
changelog header needs to be updated

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#65]
![](https://puu.sh/tRXc9/ac300c643d.png)

**Comment by Sarcalogo** [comment]
Technically all of that is true because this is /tg/ code with Hippie stuff added.

**Comment by cacogen** [comment]
there's already a partially updated header in the files (still needs the link to the issue tracker updated), the changelog just hasn't been updated with it

**Comment by j-mie** [comment]
yeah, I fucked up - fixed now :).
