### ISSUE TITLE
not enough opportunities to become an ash walker

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#69]
there's what, like one necrophiliac tendril each round that by default spawns three eggs? and if the people playing those three characters don't manage to find new bodies (and it's very easy to die on lavaland, especially with the shitty equipment ash walkers have access to) to drag to it without dying that's it?

**Comment by yobob591** [comment]
Correction, there's one tendril that spawns one every 6 rounds or so. I don't think we need more tendrils, but it should be a guaranteed spawn

**Comment by WallaceShark** [comment]
There's a fuckton of opportunities to rejoin the round in Lavaland besides the ash walkers. There's free golems, pod vaults, crashed prisoners, hermits, syndie relay station, beach biodome, space bars, and a space hotel off the top of my head. One or more of these spawn every round.

What makes ash walkers worthy of being a priority spawn over everything else?

**Comment by yobob591** [comment]
Cause they are cooler

**Comment by cacogen** [comment]
@WallaceShark 
something about building a tribe from scratch, fighting monsters and building up your loot/equipment is a lot more fun to me than doing tedious research you've done a thousand rounds before that's pointless because you're sequestered away on a syndicate base and have nobody to show off your neat shit to or botany in a room you can't leave or those hospitality roles you mentioned where nobody ever goes and where there's no purpose outside of roleplaying (which nobody ever does on hippie anyway).

@yobob591 
>it should be a guaranteed spawn

yeah, i agree. that's what i wanted initially but i don't know enough to figure out how to make ruins guaranteed to spawn.

**Comment by WallaceShark** [comment]
Perhaps you could hard map it into the lavaland Z level. Make it a permanent feature like the mining and labor camps.

**Comment by yobob591** [comment]
If it was a permanent location it would be gamed since there's good loot in there such as an RCD and sing generator and AI combat software upgrade

**Comment by Pyko1** [comment]
also mobs can spawn right outside of ashwalker base and jsut break the spawner.

**Comment by ghost** [comment]
'im ded pls let me get back into the round so i can self antag as a ligger'

lets not

**Comment by PopNotes** [comment]
fuck off roma

**Comment by ghost** [comment]
fuck lavaland

**Comment by yobob591** [comment]
That's extra gay @Pyko1

If we could get ashligger to spawn each round but in a random location that would be great

**Comment by yobob591** [comment]
@BTFO

It's not like assliggers ever even get on station, and even if they do due to incompetent miners they can't use guns and are easily robusted by sec

**Comment by yobob591** [comment]
If it becomes a real problem just make them unable to use the shuttle console like xenomorphs

**Comment by Pyko1** [comment]
yeah im thinking of remapping the ashligger template to some kind of hut and fences around that is at leastly slighly larger and have dirt few dirt plots to farm, and maybe couple more eggs.
And maybe somekind of crap forge that can make sheet to be used some crappy melee/armor upgrades.

**Comment by Spacedong** [comment]
cacogen is gay and wants to be a powergamer

**Comment by Pyko1** [comment]
I mean ashliggers are hardly a threat usually, and they help to keep players on server when they are "dead".
I see no harm making it at least a more common, and making their spawn a bit more safer against mining mobs.

Main difference between Ash Liggers, and the domesticated ligers aka Liggerus Greytidius, is that the ash liggers arent on the fucking station so they arent an issue.

**Comment by cacogen** [comment]
@BTFO 
>'im ded pls let me get back into the round so i can self antag as a ligger'

there's never anyone on mining and the likelihood of you getting to the shuttle is very slim with all the rock, lava and monsters blocking your path. even if you do, it's one poorly armed lizard who's immediately obvious as an outsider to everyone who sees them. oh, and the nogunz thing.

and you act like more antags to fight/conflict is a bad thing. if they've put in the work to get to the station they deserve to be able to fight.

@Spacedong 

when i saw in my notifications you'd commented on this i thought "spacedong is a faggot" and sure enough here we are

**Comment by ghost** [comment]
> cacogen is gay and wants to be a powergamer

what @Spacedong said

**Comment by JohnGinnane** [comment]
Fixed in #135
