### ISSUE TITLE
.dme file not the same as directory name, so safety checks on running .dmb

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#71]
the .dme is still called tgstation.dme so it compiles into tgstation.dmb. if the dmb file isn't the same as the directory name (in this case hippiestation13-rebase) then safety checks happen when it runs, so you get spammed with >100 pop-up windows asking you whether each file is safe to run when you want to test your code.

renaming the .dme file seems to fix it without issue.

**Comment by JohnGinnane** [comment]
Interesting, the dme was called the same in oldcode and first rebase and I didnt get these issues. Have you tried running dreammaker as administrator?

**Comment by cacogen** [comment]
just tried it then. running dreamseeker as admin didn't disable safety checks. i also tried running dreammaker as admin and recompiling the .dmb file and then running it through dreammaker but that didn't help either.

**Comment by j-mie** [comment]
I don't have this issue here, odd. Try setting BYOND's security setting to Trusted instead of Safe or Ultrasafe.

**Comment by KittyKathy** [comment]
You are doing it wrong, you run a test server using dream daemon and join it from there it won't spam you with safety checks well at least it does not for me.

**Comment by cacogen** [comment]
you should just be able to hit run through dream maker

**Comment by cacogen** [comment]
anyway, seems like no one cares and it's easy to fix, so
