### ISSUE TITLE
handle_fall() runtime during roundstart ruin placement

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#74]
![](https://puu.sh/tS8d9/f166faf140.png)

**Comment by JohnGinnane** [comment]
Is this a clean install?

**Comment by cacogen** [comment]
the code has been modified, but the parts i modified (variables regarding ash walkers and their nests) had nothing to do with this.

i tried to look for the dead mob to see what spawned it but because it has no mind it doesn't show up in orbit or jump to mob

**Comment by j-mie** [comment]
I think the Crashed Ship explodes on spawn, hence the runtimes on mob AI behavior - not a huge issue, but should be fixed.

**Comment by KittyKathy** [comment]
The reason it does that explosion is that that it spawns those loot crates and mobs near each other and the mobs bump into the loot crate attacking it and breaking it.
When you try to break those crates open with force it explodes as a anti-theft mechanic which exposes the area to space killing those mobs and making them fall when they die.

**Comment by JohnGinnane** [comment]
Should we remove the loot crates if they're likely to be destroyed by mobs? Replace them with crates that don't explode or maybe make the crates more resistance to damage?

**Comment by KittyKathy** [comment]
Well in pre rebase the crates would not explode when broken open so we could do that unless tg made the loot better and added that so it would be harder to get that loot.
The easiest solution without changing how anything works would be to just remap them away from mobs like behind a vault or something in that ship.

**Comment by Poojawa** [comment]
It's an issue with update_canmove()

https://github.com/tgstation/tgstation/pull/20098 similar to this, but no-one's gotten around to fixing it yet
