### ISSUE TITLE
examining a jumpsuit without sensors: "Its vital tracker and tracking beacon appear to be enabled."

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#77]

**Comment by JohnGinnane** [comment]
Looking at https://github.com/HippieStation/HippieStation13-rebase/blob/42915e2f0fc726df31f1cebd7f3206907862c391/code/modules/clothing/clothing.dm#L593 this shouldn't be possible. Can you get it to happen consistently?

**Comment by cacogen** [comment]
Yeah. I encountered this while playing an Ash Walker over different rounds. Every time I examined my uniform it said that.

**Comment by JohnGinnane** [comment]
https://github.com/HippieStation/HippieStation13/blob/42915e2f0fc726df31f1cebd7f3206907862c391/code/modules/clothing/clothing.dm#L515 I believe is the cause. Easy to fix
