### ISSUE TITLE
Travis can't handle emojis

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStationArchive/HippieStation13-2#85]
😢

**Comment by JohnGinnane** [comment]
Apparently it should be capable: https://github.com/travis-ci/travis-ci/pull/374

**Comment by JohnGinnane** [comment]
What we got: https://travis-ci.org/HippieStation/HippieStation13-rebase/jobs/199272752

**Comment by j-mie** [comment]
Travis does - our changelog script doesn't - I suspect BYOND doesn't either so that was a mistake.
