### ISSUE TITLE
Random Ruin: 'Vault' is off the blacklist

### ISSUE THREAD

**Issue by TheOneAndOnlyCreeperJoe** [HippieStationArchive/HippieStation13-2#93]
a giant meme ruin that literally has 100+ faithless; that is way too jarring on the Master Controller for virtually no purpose. We had it on the blacklist in our previous version of the rebase.

**Comment by j-mie** [comment]
`_maps/RandomRuins/LavaRuins/lavaland_surface_ww_vault.dmm` is blacklisted now.
