### ISSUE TITLE
Objects cannot be removed from pocket objects

### ISSUE THREAD

**Issue by tortellinitony** [HippieStationArchive/HippieStation13-2#98]
/obj/item/weapon/storage/internal/pocket

Objects can be placed into them, but not removed

For example: shoes, butts, etc.

Find this in code/game/objects/items/weapons/storage/internal.dm

**Comment by Spacedong** [comment]
but it works fine..........?

**Comment by Spacedong** [comment]
I can remove shit from my pockets just fine on the live server bud

**Comment by tortellinitony** [comment]
that's not what I'm talking about

**Comment by Spacedong** [comment]
what??????????????

**Comment by JohnGinnane** [comment]
To shed some light, your butt has a container in it which you can open by stripping down, setting to grab intent, aiming a groin and clicking. After a while it opens two slots which you can put items into put clicking on the icons doesn't do anything.

**Comment by JohnGinnane** [comment]
The detective's hat works in that you can take the item from it without issue (even while it's on your head) so this must be an issue with when butts were ported

**Comment by tortellinitony** [comment]
I'll compile the old rebase one, and if it works then I'll recheck the code

**Comment by j-mie** [comment]
Fixed.
